---
apiVersion: apps/v1
kind: Deployment

spec:
  replicas: 1

  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - image: venuszpli/myweb:1
        imagePullPolicy: Always
        name: myweb
